import Head from "next/head";
import Album from "../components/Album";
import Default from "../layouts/Default";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>STEM Conglomerate - MCHS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Album />
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <Default>{page}</Default>;
};
